### ISSUE TITLE
How can I change the keyboard layout to look like a dropbox passcode layout

### ISSUE THREAD

**Issue by umanusorn** [Philio/PinEntryView#10]
Your work is awesome!

How can I change the keyboard layout to look like a dropbox passcode layout.

![2015-08-13 13 20 00](https://cloud.githubusercontent.com/assets/1754362/9243706/2336ea48-41be-11e5-8b41-c08385d2c026.png)

**Comment by Philio** [comment]
They probably just added the buttons to the layout directly. I don't think that would work well with this widget because it's intended to use the soft keyboard and avoid the need for this kind of thing.

**Comment by umanusorn** [comment]
ok
