### ISSUE TITLE
Always show the keyboard

### ISSUE THREAD

**Issue by umanusorn** [Philio/PinEntryView#11]
When user press back the keyboard will be hide.
I want to finish() when user press back.
I tried to override some medthods
1. https://stackoverflow.com/questions/11965961/android-custom-edittext-and-back-button-override
   this way will cause runtime error cannot cast your object to my object
   pinEntryView = (LockEditText) findViewById(R.id.pinView);

Here is my obj
public class LockEditText extends PinEntryView {
/\* Must use this constructor in order for the layout files to instantiate the class properly */
public LockEditText(Context context, AttributeSet attrs)
{
    super(context, attrs);
    // TODO Auto-generated constructor stub
}

@Override
public boolean onKeyPreIme (int keyCode, KeyEvent event)
{
    // Return true if I handle the event:
    // In my case i want the keyboard to not be dismissible so i simply return true
    // Other people might want to handle the event differently
    System.out.println("onKeyPreIme " +event);
    return true;
}

}

**Comment by Philio** [comment]
I would not recommend trying to break a standard Android convention. Keep the UX that Google give you so that you don't confuse users.

**Comment by umanusorn** [comment]
ok
