### ISSUE TITLE
Attribute name conflict with another library

### ISSUE THREAD

**Issue by xsveda** [Philio/PinEntryView#3]
There is conflict when I try to use this library with `com.android.support:appcompat-v7` library as both are using same attribute names.
Gradle report following error:
`Attribute "accentColor" has already been defined`

Please consider using your custom and possibly unique prefix for all custom attributes. The comonly used standard is to use first characters of your library name:
`accentColor -> pev_accentColor`
`accentWidth -> pev_accentWidth`
etc.

**Comment by Philio** [comment]
Are you sure this collision is from this library? The library already includes AppCompat v7 and I have not encountered any issues using it within other projects using AppCompat.

**Comment by xsveda** [comment]
You are right. I got confused by Android Studio error message that is incorrect as it picks first library in your dependency list a points on it.
Anyway, the problem still occurs and the actual clash for `accentColor` attribute is with another library called https://github.com/neokree/MaterialTabs.
There is the same issue already assign to the project: https://github.com/neokree/MaterialTabs/issues/20
Still it is a good habit to use custom prefix for attributes to avoid such conflicts.
If you do not have enough time to handle this I can try to do a PR, I hope. Thanks!

**Comment by Philio** [comment]
I'll have a play around when I get back home as I'm currently fighting with the Great Firewall of China for internet connectivity.

I didn't realise that it creates attr resources as well as styleable resources, which is dumb and prevents you from giving custom views styleable attribs that are consistent with the built in widgets.

E.g. For

```
<declare-styleable name="PinEntryView">
    <attr name="accentColor" format="color" />
    ...
```

You seem to get generated:

```
R.styleable.PinEntryView_accentColor
R.attr.accentColor
```

The attr value seems unnecessary and would eliminate the problem as the `R.styleable` value is already automatically prefixed with the styleable name.

**Comment by xsveda** [comment]
Will you have time to update the library? Or should someone (me :)) help you somehow?

**Comment by Philio** [comment]
Ooops, I forgot about this, sorry!

Rather than change all the attribute names, I'm thinking that I can probably just get away with changing accentColor to pinAccentColor, hence removing the obvious conflict.

This way, it's a minimal change for anyone using the library.

**Comment by xsveda** [comment]
Yes, it is a quick win for now, but for the future, if you will do any other API breaking change, please introduce these prefixes as then the library will be almost 100% safe to use. Thanks!!!

**Comment by Philio** [comment]
At some point I will add some animations to the library so will re-evaluate this again then.
