### ISSUE TITLE
Visible Cursor for edittext

### ISSUE THREAD

**Issue by kp2912** [Philio/PinEntryView#37]
Hi,
I have to show cursor in editext. i have made setCursorVisible (true) but it isnt showing cursor.
Also i have tried to remove line SetCursorVisible because edittext have default cursor visible but still not shown.

**Comment by Philio** [comment]
The `EditText` is hidden. It's a bit of a hack to provide access to the
keyboard/input without having to write a custom implementation.

You'd probably need an alternative solution that used `EditText`s instead
of `TextView`s if you want a cursor. You might be able to tweak the way the
`TextView`s are added to the layout.

The use of `TextView` over `EditText` was deliberate to avoid having a
cursor actually, but they should be interchangeable (`TextView` is the
parent and contains the editable logic).

**Comment by kp2912** [comment]
Hi,
Thanks for suggestion.
I have changed my code as per your suggestions but it didnt work out. I have extended `EditText` to `DigitView` but it didnt showed cursor. Moreover there's now issue arises in opening keyboard on Touch now. So I have to think about different solution now. 
Post something if u find way to show cursor in this example.
