### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by jemshit** [Philio/PinEntryView#9]
I want to open keyboard on activity created automatically, how to achieve that? i have tried 
1)`.requestFocus()`
2) `InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.showSoftInput(pinEntryView, InputMethodManager.SHOW_IMPLICIT);``

**Comment by Philio** [comment]
It should behave like a normal EditText, if you run the demo you'll see the keyboard will open automatically. Have you changed some of the input setting in the manifest?

**Comment by jemshit** [comment]
nope

`PinEntryView pinEntryView;
pinEntryView = (PinEntryView) findViewById(R.id.login_second_pin);
..`

`````` <me.philio.pinentry.PinEntryView
            android:id="@+id/login_second_pin"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            app:accentType="none"
            app:digitTextColor="#FFF"
            app:digitTextSize="8sp"
            app:mask=""
            android:layout_gravity="center_horizontal"
            app:pinAccentColor="#FF6666"
            app:digitBackground="@drawable/blue_pr"
             />```

``````

**Comment by jemshit** [comment]
android 5.0

**Comment by umanusorn** [comment]
try this 

if(pinEntryView.requestFocus ()){
        getWindow ().setSoftInputMode ( WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE );
    }

it work with me

**Comment by jemshit** [comment]
great @umitems

**Comment by Philio** [comment]
Might be better to set it in the manifest, see: https://developer.android.com/training/keyboard-input/visibility.html#ShowOnStart

**Comment by ghost** [comment]
I couldn't get @umitems solution to work. Got it to work by using the following:

`private void showKeyboard(View v) {`
`v.requestFocus();`
`if(v instanceof PinEntryView){`
`((InputMethodManager)` `getSystemService(Context.INPUT_METHOD_SERVICE)).showSoftInput(((PinEntryView)` `v).getFocusedChild(), 0);`
`}`
`}`

Where `getFocusedChild` is the key. (Sorry for the bad formatting)

**Comment by ctanok** [comment]
try this

```
private void showSoftKeyboard(PinEntryView pinEntryView) {
    int childCount = pinEntryView.getChildCount();
    for (int i = 0; i < childCount; i++) {
        View v = pinEntryView.getChildAt(i);
        if (v instanceof EditText) {
            EditText editText = (EditText) v;
            //Standard code for showing soft keyboard
        }
    }
}
```
